In [40]:
import pandas as pd

In [41]:
df=pd.read_csv("/content/Combined_dataset.csv")
print("shape", df.shape)

shape (1000, 24)

#Exploration

In [42]:
display(df.head()) # head
display(df.tail()) # tail

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [44]:
df['final_price'] = df['final_price'].astype(str).str.replace('₹', '').str.replace(',', '').str.replace('"', '').astype(float).astype(int)
df[['title', 'initial_price', 'final_price']].head()

            title  initial_price  final_price
0     Lino Perros           3995         3995
1  Tommy Hilfiger           2899         2899
2           Lavie           2999         2999
3          F Gear           1675         1675
4       MYTRIDENT           2899         2899

In [45]:
df.describe()

,product_id,rating,ratings_count,initial_price,discount,final_price
count,1.000000e+03,1000.0000,1000.000000,1000.00000,879.000000,1000.000000
mean,1.713437e+07,3.6215,76.691000,2723.24100,53.503982,1706.096000
std,3.813766e+06,1.3744,241.114263,2408.69736,18.029201,1783.864472
min,5.868460e+05,0.0000,0.000000,249.00000,1.000000,199.000000
25%,1.511501e+07,3.7000,7.000000,1399.00000,44.000000,649.000000
50%,1.820890e+07,4.1000,17.000000,1999.00000,56.000000,1099.000000
75%,1.902737e+07,4.3000,58.000000,3299.00000,66.000000,2082.250000
max,2.274707e+07,5.0000,4441.000000,22199.00000,88.000000,17995.000000

Categorical Distribution

In [46]:
print(df['category'].value_counts().head(10).to_string()) #Top 10 categories

category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23

#Missing Values Handling

In [47]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)


print("columns with most missing values")
print(pd.DataFrame({'Missing Count' : missing,
                    'Missing %'     : missing_pct
}).query('`Missing Count` > 0').sort_values('Missing %', ascending=False))

columns with most missing values
                     Missing Count  Missing %
videos                         781       78.1
what_customers_said            573       57.3
variations                     562       56.2
seller_name                    301       30.1
seller_information             301       30.1
discount                       121       12.1

Fixing

In [48]:
#Videos
df.drop(columns=['videos'],inplace=True)
print('Dropped the videos column as 78.1 % values were null, which is not useful')

Dropped the videos column as 78.1 % values were null, which is not useful

In [49]:
#What_customers_said
df.drop(columns=['what_customers_said'], inplace=True)
print(f'57.3% missing + unstructured JSON string = not usable without parsing.')

57.3% missing + unstructured JSON string = not usable without parsing.

In [50]:
#seller_name and seller_info and variations
df = df.fillna({
    'seller_name'        : 'Unknown Seller',
    'seller_information' : 'Not Available',
    'variations'         : 'No Variations',
})

In [51]:
#discount
df['discount'].fillna(0,inplace=True)
print(f"discount can't be taken as a median as it can lead to losses, undefined discount in bussiness is take to be zero")

discount can't be taken as a median as it can lead to losses, undefined discount in bussiness is take to be zero

/tmp/ipykernel_16732/3696915350.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['discount'].fillna(0,inplace=True)

Verify

In [52]:

print(f'\n✅ Total remaining nulls: {df.isnull().sum().sum()}')

✅ Total remaining nulls: 0

#Filter and aggregation

In [53]:
high_rated = df[df['rating'] >= 4.0]
print(f'High-rated products (rating ≥ 4.0): {len(high_rated):,} out of {len(df):,}')
high_rated[['title', 'category', 'rating', 'initial_price']].head(7)

High-rated products (rating ≥ 4.0): 615 out of 1,000

            title              category  rating  initial_price
1  Tommy Hilfiger             backpacks     4.5           2899
2           Lavie             backpacks     4.4           2999
3          F Gear             backpacks     4.4           1675
4       MYTRIDENT             bath-robe     4.7           2899
5             H&M  bathroom-accessories     4.5           1399
6      AVI Living           bath-towels     4.0           1399
7         My Room             bedsheets     4.7           2999

In [54]:
avg_price = df['initial_price'].mean()
budget_products = df[df['initial_price'] < avg_price]
print(f'Budget products (price < average price of ₹{avg_price:}): {len(budget_products):,} products')
budget_products[['title', 'category', 'initial_price', 'discount']].head(5)

Budget products (price < average price of ₹2723.241): 662 products

         title              category  initial_price  discount
3       F Gear             backpacks           1675      52.0
5          H&M  bathroom-accessories           1399       0.0
6   AVI Living           bath-towels           1399      65.0
9   Story@home             bedsheets           2199      53.0
10   MYTRIDENT             bedsheets           2199      46.0

In [55]:
#Good deal (high rating + big discount)
best_deals = df[(df['rating'] >= 4.0) & (df['discount'] >= 50)]
print(f'Best deals (rating ≥ 4.0 AND discount ≥ 50%): {len(best_deals):,} products')
best_deals[['title', 'category', 'rating', 'initial_price', 'discount']].head(5)

Best deals (rating ≥ 4.0 AND discount ≥ 50%): 342 products

        title     category  rating  initial_price  discount
2       Lavie    backpacks     4.4           2999      65.0
3      F Gear    backpacks     4.4           1675      52.0
6  AVI Living  bath-towels     4.0           1399      65.0
7     My Room    bedsheets     4.7           2999      54.0
8     My Room    bedsheets     4.5           2999      54.0

Custom Filtering(user-input based)

In [56]:
# Get unique categories from the 'category'
unique_categories = df['category'].unique()
category_map = {i + 1: category for i, category in enumerate(unique_categories)}
print("Available categories:")
# Display the categories to the user
for num, category in category_map.items():
    print(f"{num} - {category}")
user_input = input("\nEnter category numbers separated by spaces (e.g., 1 3): ")
selected_numbers = [int(n.strip()) for n in user_input.split() if n.strip().isdigit()]
selected_categories = [category_map[num] for num in selected_numbers if num in category_map]

if selected_categories:
        filtered_products = df[df['category'].isin(selected_categories)]
        print(f"\nProducts in selected categories ({', '.join(selected_categories)}): {len(filtered_products):,} products")
        display(filtered_products[['title', 'category', 'initial_price', 'discount']].head())
else:
        print("No valid categories selected or entered.")

Available categories:
1 - backpacks
2 - bath-robe
3 - bathroom-accessories
4 - bath-towels
5 - bedsheets
6 - belts
7 - bodysuit
8 - boots
9 - boxers
10 - bra
11 - bracelet
12 - briefs
13 - camisoles
14 - candle-holders
15 - caps
16 - casual-shoes
17 - chair-cover
18 - clothing-set
19 - clutches
20 - co-ords
21 - curtains-and-sheers
22 - cutlery
23 - dinnerware
24 - dresses
25 - duffel-bag
26 - dungarees
27 - dupatta
28 - earrings
29 - ethnic-dresses
30 - face-moisturisers
31 - face-wash-and-cleanser
32 - flats
33 - flip-flops
34 - floor-mats--dhurries
35 - formal-shoes
36 - foundation
37 - gloves
38 - hair-accessory
39 - hair-brush-and-comb
40 - hair-cream-and-mask
41 - hair-masks
42 - handbags
43 - headphones
44 - heels
45 - home-fragrance-set
46 - innerwear-vests
47 - jackets
48 - jeans
49 - jumpsuit
50 - kurtas
51 - kurta-sets
52 - kurtis
53 - lipstick
54 - lounge-pants
55 - lounge-shorts
56 - lounge-tshirts
57 - mangalsutra
58 - mobile-accessories
59 - nightdress
60 - night-suits
61 - outdoor-masks
62 - palazzos
63 - perfume-and-body-mist
64 - pillow-covers
65 - ring
66 - runners
67 - sandals
68 - saree-blouse
69 - sarees
70 - scarves
71 - shampoo-and-conditioner
72 - shaving-essentials
73 - sherwani
74 - shirts
75 - shorts
76 - showpieces
77 - skirts
78 - sports-shoes
79 - sunglasses
80 - sweaters
81 - sweatshirts
82 - swim-tops
83 - table-covers
84 - thermal-bottoms
85 - tights
86 - tops
87 - towel-set
88 - track-pants
89 - trolley-bag
90 - trousers
91 - trunk
92 - tshirts
93 - tunics
94 - wall-art
95 - wallets
96 - watches
97 - yoga-mats

Enter category numbers separated by spaces (e.g., 1 3): 4 7

Products in selected categories (bath-towels, bodysuit): 3 products

              title     category  initial_price  discount
6        AVI Living  bath-towels           1399      65.0
19   Tommy Hilfiger     bodysuit           2999      40.0
20  Ed-a-Mamma Baby     bodysuit            999      30.0

In [57]:
min_price = float(input("Enter minimum price: "))
max_price = float(input("Enter maximum price: "))

price_range_products = df[(df['initial_price'] >= min_price) & (df['initial_price'] <= max_price)]
print(f'Products in price range ₹{min_price:.2f} - ₹{max_price:.2f}: {len(price_range_products):,} products')
price_range_products[['title', 'category', 'initial_price', 'discount']].head(5)

Enter minimum price: 400
Enter maximum price: 800
Products in price range ₹400.00 - ₹800.00: 84 products

               title category  initial_price  discount
23  The Souled Store   boxers            799      54.0
24            Jockey      bra            579       0.0
26             Susie      bra            749      50.0
28             Susie      bra            699      43.0
29            Tweens      bra            720      16.0

#Remove Duplicates

In [58]:
before = len(df)
dup_count = df.duplicated().sum()
print(f'Duplicate rows (exact match) : {dup_count}')

# Check for duplicate product IDs (same product listed twice)
dup_ids = df.duplicated(subset=['product_id']).sum()
print(f'Duplicate product_id entries : {dup_ids}')

# Remove all duplicates (keep first occurrence)
df.drop_duplicates(inplace=True)
df.drop_duplicates(subset=['product_id'], keep='first', inplace=True)

after = len(df)
print(f'\nRows before : {before:,}')
print(f'Rows after  : {after:,}')
print(f'Removed     : {before - after} duplicate rows')

Duplicate rows (exact match) : 0
Duplicate product_id entries : 0

Rows before : 1,000
Rows after  : 1,000
Removed     : 0 duplicate rows

No duplicates :)

#Derived columns

In [59]:
mean_price = df['initial_price'].mean()
df['price_tier'] = pd.cut(
    df['initial_price'],
    bins   = [0, mean_price * 0.5, mean_price, mean_price * 1.5, float('inf')],
    labels = ['Budget', 'Mid-Range', 'Premium', 'Luxury']
)
df[['title', 'category', 'initial_price', 'price_tier']].head()

            title   category  initial_price price_tier
0     Lino Perros  backpacks           3995    Premium
1  Tommy Hilfiger  backpacks           2899    Premium
2           Lavie  backpacks           2999    Premium
3          F Gear  backpacks           1675  Mid-Range
4       MYTRIDENT  bath-robe           2899    Premium

In [63]:
inconsistent = df[
    (df['discount'] > 0) &
    (df['final_price'] >= df['initial_price'])
]
print(f'Inconsistent rows: {len(inconsistent)}')

Inconsistent rows: 252

_ This Shows that even after applying discount the discount was not applied to final price

In [65]:
# Identify inconsistent rows
inconsistent_indices = df[(df['discount'] > 0) & (df['final_price'] >= df['initial_price'])].index

# Recalculate final_price for these inconsistent rows, rounding before converting to int
df.loc[inconsistent_indices, 'final_price'] = (df.loc[inconsistent_indices, 'initial_price'] * (1 - df.loc[inconsistent_indices, 'discount'] / 100)).round().astype(int)

# Verify the fix
inconsistent_after_fix = df[
    (df['discount'] > 0) &
    (df['final_price'] >= df['initial_price'])
]
print(f'Inconsistent rows after fix: {len(inconsistent_after_fix)}')

# Display a sample of the fixed rows to show the change
display(df.loc[inconsistent_indices, ['title', 'initial_price', 'discount', 'final_price']].head())

Inconsistent rows after fix: 0

Empty DataFrame
Columns: [title, initial_price, discount, final_price]
Index: []

In [66]:
df['final_price_numeric'] = df['final_price'].astype(str).str.replace('₹', '').str.replace(',', '').str.replace('"', '').astype(float)
df['savings_amount'] = df['initial_price'] - df['final_price_numeric']
df['savings_amount'] = df['savings_amount'].clip(lower=0)
print(f'Total savings: ₹{df["savings_amount"].sum():,.2f}')
df[['title', 'category', 'initial_price', 'final_price_numeric', 'savings_amount']].head()

Total savings: ₹1,345,048.00

,title,category,initial_price,final_price_numeric,savings_amount
0,Lino Perros,backpacks,3995,1677.0,2318.0
1,Tommy Hilfiger,backpacks,2899,1884.0,1015.0
2,Lavie,backpacks,2999,1049.0,1950.0
3,F Gear,backpacks,1675,804.0,871.0
4,MYTRIDENT,bath-robe,2899,2406.0,493.0

In [67]:
df.to_csv('processed_products.csv', index=False)
print('DataFrame saved to processed_products.csv')

DataFrame saved to processed_products.csv